<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'front' => [[], ['_controller' => 'App\\Controller\\FrontController::index'], [], [['text', '/']], [], []],
    'coach' => [[], ['_controller' => 'App\\Controller\\FrontController::coach'], [], [['text', '/coach']], [], []],
    'accueil' => [[], ['_controller' => 'App\\Controller\\FrontController::accueil'], [], [['text', '/accueil']], [], []],
    'logo' => [[], ['_controller' => 'App\\Controller\\FrontController::logo'], [], [['text', '/logo']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\FrontController::login'], [], [['text', '/login']], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\FrontController::contact'], [], [['text', '/contact']], [], []],
    'membre' => [[], ['_controller' => 'App\\Controller\\FrontController::membre'], [], [['text', '/membre']], [], []],
    'cnews' => [[], ['_controller' => 'App\\Controller\\FrontController::news'], [], [['text', '/cnews']], [], []],
    'single' => [[], ['_controller' => 'App\\Controller\\FrontController::nsingle'], [], [['text', '/single']], [], []],
    'nutrition' => [[], ['_controller' => 'App\\Controller\\FrontController::nutrition'], [], [['text', '/nutrition']], [], []],
    'recette' => [[], ['_controller' => 'App\\Controller\\FrontController::recette'], [], [['text', '/recette']], [], []],
    'shop' => [[], ['_controller' => 'App\\Controller\\FrontController::shop'], [], [['text', '/shop']], [], []],
    'shopsingle' => [[], ['_controller' => 'App\\Controller\\FrontController::shopsingle'], [], [['text', '/shopsingle']], [], []],
];
